AWSTemplateFormatVersion: 2010-09-09

Description: Deploys the base resources necessary for aws cicd.

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Iamic
        Parameters:
          - IdentityStoreId
          - InstanceArn
  Deployment:
    StackName: flagscript-organization-setup 

Parameters:
  #########
  # Iamic #
  #########
  IdentityStoreId:
    Description: The id of the identity and access management identity center directory store.
    Type: String  

  InstanceArn: 
    Description: The arn of the identity and access management identity center instance.
    Type: String

Resources:

  ##########
  # Dynamo #
  ##########
  TerraformLockTable:
    Type: AWS::DynamoDB::Table
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      AttributeDefinitions:
        - AttributeName: LockID
          AttributeType: S
      BillingMode: PROVISIONED
      DeletionProtectionEnabled: true
      KeySchema:
        - AttributeName: LockID
          KeyType: HASH
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
      ProvisionedThroughput:
        ReadCapacityUnits: 20
        WriteCapacityUnits: 20
      SSESpecification:
        SSEEnabled: false
      TableName: terraform-state-lock
      Tags:
        - Key: flagscript:account-owner:owner
          Value: flagscript
        - Key: flagscript:automation:environment
          Value: root          
        - Key: flagscript:cost-allocation:application-id
          Value: organiztion-setup
        - Key: flagscript:cost-allocation:owner
          Value: flagscript          
        - Key: flagscript:data-owner:owner
          Value: flagscript       
        - Key: flagscript:operations:owner
          Value: flagscript   
        - Key: Name
          Value: terraform-state-lock  

  #########
  # Iamic #
  ######### 
  OrgAdministratorGroup:
    Type: AWS::IdentityStore::Group
    Properties: 
      Description: Organization administrator group. Org root account only.
      DisplayName: org-administrator
      IdentityStoreId: !Ref IdentityStoreId              

  OrgAdministratorPermissionSet:
    Type: AWS::SSO::PermissionSet
    Properties:
      Description: Administrator permission set for the org root account ONLY.
      InstanceArn: !Ref InstanceArn
      ManagedPolicies: 
        - arn:aws:iam::aws:policy/AdministratorAccess
      Name: org-administrator
      Tags: 
        - Key: flagscript:account-owner:owner
          Value: flagscript
        - Key: flagscript:automation:environment
          Value: root          
        - Key: flagscript:cost-allocation:application-id
          Value: organiztion-setup
        - Key: flagscript:cost-allocation:owner
          Value: flagscript          
        - Key: flagscript:data-owner:owner
          Value: flagscript       
        - Key: flagscript:operations:owner
          Value: flagscript  
        - Key: Name
          Value: org-administrator         

  OrgAdministratorPermissionSetRootAccountAssignment:
    Type: AWS::SSO::Assignment  
    Properties:
      InstanceArn: !Ref InstanceArn
      PermissionSetArn: !GetAtt OrgAdministratorPermissionSet.PermissionSetArn
      PrincipalId: !GetAtt OrgAdministratorGroup.GroupId
      PrincipalType: GROUP
      TargetId: !Ref 'AWS::AccountId'
      TargetType: AWS_ACCOUNT

  ###############################
  # S3 - Terraform State Bucket #
  ###############################
  # Bucket to be used to maintain terraform state.
  TerraformStateBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - BucketKeyEnabled: true
            ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      BucketName: !Sub org-setup-${AWS::AccountId}-${AWS::Region}-terraform-state
      LifecycleConfiguration:
        Rules:
          - AbortIncompleteMultipartUpload:
              DaysAfterInitiation: 1
            Id: abort-failed-uploads
            Status: Enabled      
      NotificationConfiguration:
        EventBridgeConfiguration:
          EventBridgeEnabled: true             
      PublicAccessBlockConfiguration:
         BlockPublicAcls: true
         IgnorePublicAcls: true
         BlockPublicPolicy: true
         RestrictPublicBuckets: true
      Tags:
        - Key: flagscript:account-owner:owner
          Value: flagscript
        - Key: flagscript:automation:environment
          Value: root          
        - Key: flagscript:cost-allocation:application-id
          Value: organiztion-setup
        - Key: flagscript:cost-allocation:owner
          Value: flagscript          
        - Key: flagscript:data-owner:owner
          Value: flagscript       
        - Key: flagscript:operations:owner
          Value: flagscript  
        - Key: Name
          Value: !Sub org-setup-${AWS::AccountId}-${AWS::Region}-terraform-state
      VersioningConfiguration:
        Status: Enabled 

  # Bucket policy for the terraform state bucket. Enforces ssl uploads only, and forces client
  # to expect files to be encrypted at rest with aws:kms.
  TerraformStateBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref TerraformStateBucket
      PolicyDocument:
        Statement: 
          - Action:
              - s3:*
            Condition:
              Bool:
                aws:SecureTransport: false
            Effect: Deny
            Principal: '*'
            Resource: !Sub ${TerraformStateBucket.Arn}/*
            Sid: DenyInsecureConnections  
